function [Sample,Line,ET,AverageError]=createPVLforHiJACK(imagelocation, imageid, lineinterval, flat1, from1, flat2, from2, flat3, from3)
% CREATEPVLFORHIJACK takes the flat files generated by hijitreg and feeds them to the Matlab script resolveJitter4HiJACK.m
%
% INPUTS (string arguments must have single quotes, numeric arguments must not have single quotes):
%   imagelocation    './' if files are being processed in the same directory 
%   imageid          'XXX_999999_9999' where XXX is the three-letter mission phase and the 9's are the orbit and latitude numbers for a HiRISE observation ID
%   lineinterval     nn where nn is an integer number, usually 20 or 50 read from the config file for the first part of HiJACK and passed as a parameter to hijitreg.
%   flat<n>          '<flat file output from hijitreg>' 
%   from<n>          1 or -1 depending on whether the common CCD of the three pairs run through hijitreg is in the 'From' or 'Match' position. See below.
% 
% OUTPUTS:
%   A text file with the columns describing the jitter motion in terms of sample and line pixel translations at discrete ephemeris (ET) time intervals.
%   The AverageError is the average error between the derived jitter function and the original data, in pixels.
%   Summary plots are generated invisibly and saved to a .png file in the observation data directory.
%   pixelSmear is called to estimate pixel smear based on the jitter function. It writes a text file and creates a plot.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Written by Aaron Boyd and Sarah Mattson for HiROC as part of the 
%   process to describe and correct geometric distortions caused by jitter
%   in HiRISE images. Original version written approximately 6/2008.
%
% CVS ID: $Id: createPVLforHiJACK.m,v 1.2 2009/04/15 23:00:36 smattson Exp $
%
% Copyright (C) 2008 Arizona Board of Regents on behalf of the Planetary
% Image Research Laboratory, Lunar and Planetary Laboratory at the
% University of Arizona.
% 
% This program is free software; you can redistribute it and/or modify it
% under the terms of the GNU General Public License, version 2, as
% published by the Free Software Foundation.
% 
% This program is distributed in the hope that it will be useful, but
% WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
% General Public License for more details.
% 
% You should have received a copy of the GNU General Public License along
% with this program; if not, write to the Free Software Foundation, Inc.,
% 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% In the flat files, if RED4 is the 'From', use -1. If RED4 is the 'Match', use 1.
[Sample,Line,ET,AverageError, linerate, TDI]=resolveJitter4HiJACK([imagelocation,flat1], from1, [imagelocation,flat2], from2, [imagelocation,flat3], from3, lineinterval);
data=[Sample,Line,ET];

% output pixel smear values (max) and plot
[maxSmearSample, maxSmearLine, maxSmearMag] = pixelSmear(Sample,Line,ET, linerate, TDI, imagelocation, imageid);

figure(400)
set(gcf,'visible','off');
subplot(3,6,[1,2]), title(flat1,'Interpreter','none', 'FontSize', 8)
subplot(3,6,[3,4]), title(flat2,'Interpreter','none', 'FontSize', 8)
subplot(3,6,[5,6]), title(flat3,'Interpreter','none', 'FontSize', 8)
subplot(3,6,[13,15]), title('Cross-track Jitter')
subplot(3,6,[16,18]), title('Down-track Jitter')

fid=fopen([imagelocation,imageid,'_jitter.txt'], 'wt');
disp(sprintf('--------- Writing %s', [imagelocation,imageid,'_jitter.txt']));
fprintf(fid,'# Using image %s the jitter was found with an\n',imageid);
fprintf(fid,'# Average Error of %f\n',AverageError);
%fprintf(fid,'# Maximum Cross-track pixel smear %f\n', maxSmearSample);
%fprintf(fid,'# Maximum Down-track pixel smear %f\n', maxSmearLine);
fprintf(fid,'# Maximum Pixel Smear Magnitude %f\n', maxSmearMag);
fprintf(fid,'#\n# Sample                 Line                   ET \n');
fprintf(fid,'%12.16f     %12.16f     %12.9f\n', data');
fclose(fid);

saveas(400,[imagelocation,imageid,'_jitter_plot.png'],'png')

